apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Nginx with ConfigMap</title>
    </head>
    <body>
      <h1>Hello from Nginx!</h1>
      <p>ConfigMap and Secret working</p>
    </body>
    </html>