apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels: 
        app: nginx 
    spec: 
      containers:
      - name: nginx 
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        - name: secret-volume
          mountPath: /etc/nginx-secrets
          readOnly: true
      volumes: 
      - name: html-content
        configMap:
          name: nginx-cm 
          items: 
          - key: index.html
            path: index.html
      - name: secret-volume
        secret:
          secretName: nginx-secret