apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
      tier: frontend
  template:
    metadata:
      labels:
        app: django-app
        tier: frontend
    spec:
      containers:
      - name: django-app
        image: django-app:1.0.0
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: django-configmap-v1.0
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"