apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    name: http
  selector:
    app: django-app
    tier: frontend
  type: LoadBalancer