apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
    owner: team-devops
    description: "namespace_for_production_workloads"
    environment: production
    team: devops